-- Tabela de links encurtados.
--
-- O nome do arquivo segue a convencao do Flyway: V<versao>__<descricao>.sql
-- (dois underscores). Depois de aplicada, uma migration NUNCA e editada -- o
-- Flyway guarda o checksum de cada arquivo e recusa subir se ele mudar.
-- Correcao de schema se faz com uma nova migration (V2, V3...).

CREATE TABLE links (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(16)   NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL,
    expires_at   TIMESTAMPTZ
);

-- Indice unico no codigo curto: resolve dois problemas de uma vez.
--
-- 1. Correcao: e a garantia real contra colisao. A checagem em Java
--    (existsByCode antes do insert) tem uma janela entre a consulta e a
--    gravacao em que outra requisicao pode inserir o mesmo codigo. O banco
--    fecha essa janela.
-- 2. Desempenho: o redirecionamento (Etapa 4) busca sempre por code. Sem
--    indice, cada acesso viraria varredura da tabela inteira.
CREATE UNIQUE INDEX idx_links_code ON links (code);

-- TIMESTAMPTZ e nao TIMESTAMP: o tipo sem fuso guarda "10:00" sem dizer 10:00
-- de onde. Com usuarios e servidores em fusos diferentes, isso vira bug de
-- expiracao de link.
