-- Registro de acessos aos links curtos.
--
-- Uma linha por clique. A tabela cresce muito mais rapido que "links": um link
-- popular gera milhares de linhas aqui. Por isso ela nasce ja indexada para as
-- consultas que o endpoint de estatisticas faz.

CREATE TABLE clicks (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id    BIGINT       NOT NULL REFERENCES links (id) ON DELETE CASCADE,
    clicked_at TIMESTAMPTZ  NOT NULL,
    referrer   VARCHAR(2048),
    user_agent VARCHAR(512),

    -- NAO e o IP: e o SHA-256 do IP com um segredo da aplicacao.
    --
    -- Endereco IP e dado pessoal (LGPD art. 5, I -- permite identificar uma
    -- pessoa quando combinado com outras informacoes). Guardar o hash permite
    -- contar visitantes distintos, que e a unica coisa que a estatistica
    -- precisa, sem manter o dado original. Um vazamento do banco nao entrega os
    -- IPs de quem clicou.
    ip_hash    VARCHAR(64)
);

-- Indice composto na ordem em que as consultas filtram: primeiro o link,
-- depois a faixa de datas. Serve tanto para "quantos cliques teve este link"
-- quanto para "cliques deste link nos ultimos 7 dias".
--
-- A ordem das colunas importa: um indice em (clicked_at, link_id) nao ajudaria
-- a primeira consulta, porque ela nao filtra por data.
CREATE INDEX idx_clicks_link_clicked_at ON clicks (link_id, clicked_at DESC);
